### ISSUE TITLE
Highlight all our data sources

### ISSUE THREAD

**Issue by iobik** [soichih/apred#40] opened 2020-10-05 03:06 UTC
State the name of the data sources.  This approach will help to answer questions about the authenticity and authority of the data we are presenting on the platform.

**Comment by soichih** [comment] 2020-10-05 19:34
For example, add this sentence under the Disaster Resilience section

```
The resilience scores are calculated using information collected by the U.S. Census using formulas defined by Cutters, et all. 
```

**Comment by soichih** [comment] 2020-10-28 15:52
I've added the sentence that I proposed under disaster Declarations tab. I am closing this as I believe is duplicate of #39.

**Closed by soichih** 2020-10-28 15:52 UTC
Labels: high
